/* global Bento */
Bento.prototype.DefaultConfig = {
	applicationContext:	"media.mtvnservices.com",
	applicationName:	"Network Player",
	applicationOrigin:	null,
	applicationType:	null,
	comscoreAdTracking:	true,
	comscoreEnabled:	false,
	countryCode:	"COUNTRY_XX",
	customFields:	{},
	demdexEnabled:	false,
	demdexEndCallEnabled:	false,
	freewheelEnabled:	false,
	group:	null,
	nielsenEnabled:	false,
	omnitureAdTrackingEnabled:	false,
	omnitureCharSet:	"ISO-8859-1",
	omnitureDataCenter:	"112",
	omnitureEnabled:	true,
	omnitureEndslateTracking:	false,
	omnitureFirstPartyServer:	"sc.mtv.com",
	omnitureHeartbeatsDisabled:	true,
	omnitureLiveEventBeaconFreq:	180,
	omnitureLiveEventHeartbeatsDisabled:	false,
	omnitureLiveEventTrackingEnabled:	false,
	omnitureMediaTrackingEnabled:	true,
	omniturePathContext:	"video/net/",
	omnitureSuite:	"viamtv",
	omnitureVisitorNamespace:	false,
	playerURL:	null,
	referrer:	"media.mtvnservices.com"
};